
[build.environment]
  NODE_VERSION = "16.20.0"
  CI = "false"

[build]
  base = "frontend"
  publish = "/opt/build/repo/frontend/build"
  command = "CI=false npm run build"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000
